### ISSUE TITLE
Hi! Nice Project! 

### ISSUE THREAD

**Issue by Skanouch** [tungrix/bybit_copy_trade#1]
Hello, 
This project is really nice,  i'm new to python and dev in general, i do undestand what the script does and how it was created,  what i'm not sure is how it create orders to bybit, i've made some tests and it gets the new trades from traders, but he did not send order to bybit.
I've created the json with api_key etc.. Do i need to add some parameters to this file ? 
Do we need to run the script to refresh trade list? I saw the script have to do it on it's own, but mine stays at 
INFO :  *****
Can't wait to have your answer :D Thanks !

**Comment by tungrix** [comment]
1. It needs to wait the followed principal trader to open new trades, then the program will open new trades too!
2. In config.json, except api_key you also need api_secret as well
3. The script will refresh the opened trade list

**Comment by Skanouch** [comment]
Thank you Tungrix, working nicely, the only issue is now this : 
Error sign! origin_string[api_key=******remove******&close_on_trigger=false&order_type=market&qty=0.001&recv_window=5000&reduce_only=false&side=buy&symbol=btcusdt&time_in_force=goodtillcancel&timestamp=1664295560033] (ErrCode: 10004) (ErrTime: 16:19:20).
Request → POST https://api.bybit.com/private/linear/order/create: {'api_key': '******remove******', 'close_on_trigger': False, 'order_type': 'Market', 'qty': 0.001, 'recv_window': 5000, 'reduce_only': False, 'side': 'Buy', 'symbol': 'BTCUSDT', 'time_in_force': 'GoodTillCancel', 'timestamp': 1664295560033, 'sign': 'd80906038feed4a93188a3f6142fe7d5ba22e6a2f93a1b44d73701f2f49bc295'}.
I'm not sure what to do

**Comment by tungrix** [comment]
Could you trace back which line of code generate this error? And what are the input parameters if it is a function

**Comment by Skanouch** [comment]
Hello! Sure, here are the original error i had
From 
           ` value = Config._CONFIG.get(key).get(param, {})`
Error : 
```
'str' object has no attribute 'get'
  File "\\WSL$\UBUNTU-20.04\home\morgan\bybit_copy_trade\lib\utils.py", line 59, in get_config_value
    value = Config._CONFIG.get(key).get(param, {})
  File "\\WSL$\UBUNTU-20.04\home\morgan\bybit_copy_trade\main.py", line 26, in __init__
    api_key=self.config.get_config_value(param="api_key"),
  File "\\WSL$\UBUNTU-20.04\home\morgan\bybit_copy_trade\main.py", line 116, in <module>
    bybit_copy_trade = Bybit_copy_trade()
```
Then i've deleted the `.get(param, {})` from `value = Config._CONFIG.get(key).get(param, {})`  if it work. 
The script run Without issue. That's strange. 

Then i let the bot wait for new entry from traders, and have this error from the logger : 

```
Error sign! origin_string[api_key=h9EuZWam6pvdPEaKU5&close_on_trigger=false&order_type=market&qty=0.1&recv_window=5000&reduce_only=false&side=buy&symbol=linkusdt&time_in_force=goodtillcancel&timestamp=1664373301743] (ErrCode: 10004) (ErrTime: 13:55:01).
Request → POST https://api.bybit.com/private/linear/order/create: {'api_key': 'h9EuZWam6pvdPEaKU5', 'close_on_trigger': False, 'order_type': 'Market', 'qty': 0.1, 'recv_window': 5000, 'reduce_only': False, 'side': 'Buy', 'symbol': 'LINKUSDT', 'time_in_force': 'GoodTillCancel', 'timestamp': 1664373301743, 'sign': '2a9ee7452bb7e66859c6ddb364cc3b6101e69a2f6defae277c3de26b1b2de3bc'}.
Error sign! origin_string[api_key=h9EuZWam6pvdPEaKU5&close_on_trigger=false&order_type=market&qty=0.1&recv_window=5000&reduce_only=false&side=buy&symbol=linkusdt&time_in_force=goodtillcancel&timestamp=1664373301916] (ErrCode: 10004) (ErrTime: 13:55:02).
Request → POST https://api.bybit.com/private/linear/order/create: {'api_key': 'h9EuZWam6pvdPEaKU5', 'close_on_trigger': False, 'order_type': 'Market', 'qty': 0.1, 'recv_window': 5000, 'reduce_only': False, 'side': 'Buy', 'symbol': 'LINKUSDT', 'time_in_force': 'GoodTillCancel', 'timestamp': 1664373301916, 'sign': '84f9add42b93cb48081ed0abf2d08cc834c13ceac989c9a9fb75867b6e16c311'}.
Error sign! origin_string
```

My config.json is like this : 
```
{
		"api_key" : "h9EuZWam6pvdPEaKU5",
		"api_secret" : "**************************************"
}
```
Let me know ! Thank you

**Comment by tungrix** [comment]
The content inside config file should be 
```
{
    "API": {
        "api_key": "PPWOVSPUILZDNTKTXJ",
        "api_secret": "RBJPNADATKYSRZVILUCENRNXZGICXHFUBUBF"
    }
}
```
I will update the code and config soon.

**Comment by tungrix** [comment]
The content inside config file should be 
```
{
    "API": {
        "api_key": "",
        "api_secret": ""
    }
}
```
I will add some error handler and reminder in the code and add a readme file soon.

**Comment by Skanouch** [comment]
Hello! 

Just to let you know that it is working like a charm. 

Thank you 🦾
