### ISSUE TITLE
First request

### ISSUE THREAD

**Issue by Skanouch** [tungrix/bybit_copy_trade#2]
Hey ! 

Again :D I'm using your script for few days now, i wonder if you ever will update a qty modifier ? 
Something that could use a multiple for each min_qty, let's say BTC min_qty = 0.001 * 5 then you could enter positions with 0.005 BTC instead of min_qty by default. 
I was thinking also about USDT directly, which mean the script will only use that amout per trade, whatever leverage you have on the exchange. 

I did try to figure out myself, but my skills are too low at the moment. I did understand that you get those min_qty from API but i can't figure out how i change it. I'm strugling on this one for 4 days :D 
Hope you could help ! 
Thank you very much !
Cheers !

**Comment by tungrix** [comment]
I will release a new version soon, which can set `invest_amount` in usdt in the config.json to achieve what you struggled. Hope it helps.

**Comment by Skanouch** [comment]
Good Morning Sir, 
Hope everything doing well for you ?
Thank you for the update, i'll give it a try and let you know if i find some farts :D

**Comment by Skanouch** [comment]
Did not wanted to close the request. Bad miss click

**Comment by tungrix** [comment]
If you have any questions, please create a new issue~
