### ISSUE TITLE
You're right, something went wrong

### ISSUE THREAD

**Issue by Skanouch** [tungrix/bybit_copy_trade#4]
Hi, 

Find here the log error : 
10/06/2022 01:03:51PM - ERROR: Param validation for 'qty' failed on the 'required' tag (ErrCode: 10001) (ErrTime: 11:03:51).
Request → POST https://api.bybit.com/private/linear/order/create: {'api_key': 'REMOVED', 'close_on_trigger': False, 'order_type': 'Market', 'qty': 0, 'recv_window': 5000, 'reduce_only': False, 'side': 'Buy', 'symbol': 'ADAUSDT', 'time_in_force': 'GoodTillCancel', 'timestamp': 1665054231406, 'sign': '74ff58af0b0683c8f6959eea4daecbac6f3e2729dc3906d925fa62caa2d9f475'}.

The qty send is 0, just to let you know.

**Comment by tungrix** [comment]
Under utils.py `place_market_order` function, `qty = self.lot_size_dict.get(symbol, 0)` , symbol is parameter instead of string, will fix the bug in the next update. Thanks for reporting.

**Comment by Skanouch** [comment]
Hi!
I’ve been trying your development branch! Really nice update, can’t wait to see how it perform. 
Did some testing on it, updated python 3.10.8
But when it open a position, he closes them few seconds later. 
cumulative = true or false is the same.
Same as master branch. Open and close few seconds later. Do you have the same behavior ?
